### ISSUE TITLE
Where do I get an App ID?

### ISSUE THREAD

**Issue by hboylan** [gotwalt/redlink#1]
Trying to fork and extend this to control thermostats, but how do I get a valid App ID?

Redlink::Endpoint::InvalidSessionError (Redlink::Endpoint::InvalidSessionError)

**Comment by gotwalt** [comment]
The App ID in the readme is definitely NOT a valid App ID. I'm not sure where you might get a working one, but some knowledge of ROT13 might help.

**Comment by hboylan** [comment]
Is <a href="https://rs.alarmnet.com/TC2API/TC2.asmx?WSDL">this</a> the full SOAP doc from alarmnet?

**Comment by gotwalt** [comment]
Yeah, it was at the time I did it. Might need a refresh, but full operations are in there for changing settings. To get this far I did a MITM on the iOS app using Charles Proxy. A packet dump of changing a thermostat at my house is available at http://d.gotwalt.com/3d153c0N2d3M if you want to see what it's doing.

**Comment by hboylan** [comment]
I don't know how to view that .chls file, but I get the idea. This would be awesome if they'd open up the API.

The application I wanted to use this for is non-proprietary for a competition with the DOE since it would look better if we controlled it instead of launching the Honeywell app. They don't want to work with us even though it's free advertising for them.

**Comment by gotwalt** [comment]
Right, it's really backwards (related: backwards SOAP API). If you download
Charles (http://www.charlesproxy.com/) you can open that file and see the
http logs going back and forth. There's probably more than enough in there
to finish implementing thermostat control. Shouldn't be hard, just haven't
had time to do it.

**Comment by hboylan** [comment]
You're the man @gotwalt I'm going to spend the next week hacking this. I may come up with a question or two, but expect a pull request soon.

...Also wondering if their AppID is dynamic or what, we'll see

**Comment by gotwalt** [comment]
App ID is hardcoded. They'd have to kill a minimum of all existing iOS
clients and replace the key to shut it down. And then it'd be interceptable
again, unless they show a level of engineering prowess that I don't see
coming from them.

**Comment by hboylan** [comment]
Looking at all the request/responses from that MITM I see data from thermostat commands, but nothing with any kind of AppID encrypted or otherwise.
